name: Install and Commit with SimpleGit

on:
  workflow_dispatch:  # Allows manual execution from the Actions tab

jobs:
  setup-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Install Git
        run: sudo apt update && sudo apt install -y git

      - name: Check Git Version
        run: git --version

      - name: Authenticate with GitHub
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global credential.helper store
          echo "https://${{ secrets.PAT_TOKEN }}:x-oauth-basic@github.com" > ~/.git-credentials

      - name: Verify Git Authentication
        run: |
          if git ls-remote https://github.com/${{ github.actor }}/coolrobloxgamerboy17.git &>/dev/null; then
            echo "Authentication Successful"
          else
            echo "Authentication Failed" && exit 1
          fi

      - name: Install Node.js and SimpleGit
        run: |
          npm install -g simple-git moment jsonfile random

      - name: Create and Commit Files
        run: |
          # Navigate to the repository
          git clone https://github.com/${{ github.actor }}/coolrobloxgamerboy17.git
          cd coolrobloxgamerboy17

          # Function to generate random commit dates
          make_commits() {
            for year in $(seq 1999 $(date +%Y)); do
              for ((i = 0; i < 100; i++)); do
                x=$((RANDOM % 54))   # Random weeks
                y=$((RANDOM % 7))    # Random days
                date=$(date -d "$year-01-01 +$((x * 7 + y)) days" +"%Y-%m-%dT%H:%M:%S")

                # Create a new file and write to it
                echo "{\"date\":\"$date\"}" > data.json

                # Commit the file with the generated date
                git add data.json
                GIT_COMMITTER_DATE="$date" git commit -m "Commit for $date" --date="$date"

                # Push the commit to the repository using the PAT in the URL
                git push https://${{ secrets.PAT_TOKEN }}:x-oauth-basic@github.com/${{ github.actor }}/coolrobloxgamerboy17.git main
              done
            done
          }

          make_commits

          # Clean up
          cd ..
          rm -rf coolrobloxgamerboy17
