name: Install and Commit with SimpleGit

on:
  workflow_dispatch:  # Allows manual execution from the Actions tab

jobs:
  setup-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Install Git
        run: sudo apt update && sudo apt install -y git

      - name: Check Git Version
        run: git --version

      - name: Authenticate with GitHub
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global credential.helper store
          echo "https://${{ secrets.GH_PAT }}@github.com" > ~/.git-credentials
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

      - name: Verify Git Authentication
        run: |
          if git ls-remote https://github.com/${{ github.actor }}/coolrobloxgamerboy17.git &>/dev/null; then
            echo "Authentication Successful"
          else
            echo "Authentication Failed" && exit 1
          fi

      - name: Install Node.js and SimpleGit
        run: |
          npm install -g simple-git

      - name: Create and Commit Files
        run: |
          # Navigate to the repository
          git clone https://github.com/${{ github.actor }}/coolrobloxgamerboy17.git
          cd coolrobloxgamerboy17

          # Loop through years from 1999 to the current year
          for year in $(seq 1999 $(date +%Y)); do
            # Check if the commit already exists
            if git rev-list -1 --count --all --grep="Commit for ${year}"; then
              echo "Commit for ${year} already exists. Skipping..."
              continue
            fi

            # Create a new file and write to it
            echo "This is a commit for the year ${year}" > "commit_file_${year}.txt"

            # Create a new branch for the year
            git checkout -b "year-${year}"

            # Commit the file with a specific date
            git add "commit_file_${year}.txt"
            GIT_COMMITTER_DATE="${year}-01-01" git commit -m "Commit for ${year}"

            # Push the commit to the repository
            git push origin "year-${year}"

            # Return to the main branch for the next iteration
            git checkout main
          done

          # Clean up
          cd ..
          rm -rf YourRepo
