name: Update README

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  ProfessionalCrasherOuter:
    runs-on: ubuntu-latest

    steps:
    - name: Crashout Repo
      uses: actions/checkout@v2

    - name: List Crashout Victims
      run: |
        echo "\nListing contents of the repository:"
        ls -R

    - name: Update README
      run: |
        readFile="README.md" # also change it at the bottom
        imagesDir="Images"
        size=(86 40)

        imageMark=""
        > "$readFile"

        beforeCont="# free cool stuff\n"
        afterCont="<sub><sup> i legit spent ages automating ts (and its on a new line)</sup></sub>"

        echo -e "$beforeCont" >> "$readFile"

        declare -A imageGroups
        if [ -d "$imagesDir" ]; then
          for image in "$imagesDir"/*; do
            if [[ "$image" == *.jpg || "$image" == *.jpeg || "$image" == *.png || "$image" == *.gif ]]; then
              extension="${image##*.}"
              extension="${extension,,}"
              imageGroups["$extension"]+="$image "
            fi
          done
        fi

        for extension in "${!imageGroups[@]}"; do
          images="${imageGroups[$extension]}"
          for image in $images; do
            imageName=$(basename "$image")
            imageUrl="https://raw.githubusercontent.com/${{ github.repository }}/main/$imagesDir/$imageName"
            profileLink="https://github.com/${{ github.repository }}"
            imageMark+="[<img src=\"$imageUrl\" width=\"${size[0]}\" height=\"${size[1]}\">]($imageUrl) "
          done
        done

        if [ -z "$imageMark" ]; then
          echo "no images found"
        else
          echo -e "$imageMark" >> "$readFile"
        fi
        echo -e "$afterCont" >> "$readFile"

    - name: Commit changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        readFile="README.md" # also change it at the top

        git config --local user.name "GitHub Action"
        git config --local user.email "action@github.com"
        if [ -f "$readFile" ]; then
          git add "$readFile"
          git commit -m "Update README" || echo "no commit"
          git push
        else
          echo "$readFile does not exist in the repository's root directory."
        fi
