name: Update README with Images

on:
  push:
    branches:
      - main  # Change this to your default branch if different
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update README with Images
      run: |
        # Set variables
        README_FILE="README.md"
        IMAGES_DIR="Images"
        IMAGE_MARKUP=""

        # Check if images directory exists
        if [ -d "$IMAGES_DIR" ]; then
          # Loop through all images in the images directory
          for img in "$IMAGES_DIR"/*; do
            # Check if the file is an image (you can customize this check)
            if [[ "$img" == *.jpg || "$img" == *.jpeg || "$img" == *.png || "$img" == *.gif ]]; then
              # Add image markdown to the IMAGE_MARKUP variable
              IMAGE_MARKUP+="\n![Image](./$img)\n"
            fi
          done
        fi

        # Append images to the README file
        echo -e "$IMAGE_MARKUP" >> "$README_FILE"

    - name: Commit changes
      run: |
        git config --local user.name "GitHub Action"
        git config --local user.email "action@github.com"
        git add "$README_FILE"
        git commit -m "Update README with images from the images directory" || echo "No changes to commit"
        git push
