name: Update README with Images Folder

on:
  workflow_dispatch:
  push:
    paths:
      - 'Images/**'
  schedule:
    - cron: '0 0 * * *'  # Runs daily

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Image List
        run: |
          echo "## Images Folder Contents" > IMAGES.md
          for file in Images/*; do
            echo "- ![$(basename $file)](https://raw.githubusercontent.com/${{ github.repository }}/main/$file)" >> IMAGES.md
          done

      - name: Update README
        run: |
          sed -i '/<!-- IMAGES_START -->/,/<!-- IMAGES_END -->/d' README.md
          echo '<!-- IMAGES_START -->' >> README.md
          cat IMAGES.md >> README.md
          echo '<!-- IMAGES_END -->' >> README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Updated README with latest images" || exit 0
          git push
