name: Update README with Images

on:
  push:
    branches:
      - main  # Change this to your default branch if different
  workflow_dispatch:  # Allow manual triggering of the workflow

permissions:
  contents: write  # Allows the workflow to push changes

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: List repository contents
      run: |
        echo "Listing contents of the repository:"
        ls -R  # List all files recursively to see the directory structure

    - name: Update README with Images
      run: |
        # Set variables
        README_FILE="README.md"
        IMAGES_DIR="Images"
        IMAGE_MARKUP=""
        BEFORE_CONTENT="# Before Images\n\n"  # Add your markdown content before images

        # Clear the README file
        > "$README_FILE"  # Truncate the README file to clear its contents

        # Check if images directory exists
        if [ -d "$IMAGES_DIR" ]; then
          # Loop through all images in the images directory
          for img in "$IMAGES_DIR"/*; do
            # Check if the file is an image (you can customize this check)
            if [[ "$img" == *.jpg || "$img" == *.jpeg || "$img" == *.png || "$img" == *.gif ]]; then
              # Extract image name from the path
              IMAGE_NAME=$(basename "$img")
              # Construct the image URL
              IMAGE_URL="https://raw.githubusercontent.com/${{ github.repository }}/main/$IMAGES_DIR/$IMAGE_NAME"  # Ensure branch is correct
              PROFILE_LINK="https://github.com/${{ github.repository }}"  # Adjust to your profile link

              # Add image markup to the IMAGE_MARKUP variable
              IMAGE_MARKUP+="[<img src=\"$IMAGE_URL\" width=\"86\" height=\"40\">]($PROFILE_LINK)\n"
            fi
          done
        fi

        # Check if IMAGE_MARKUP is not empty before appending to README
        if [ -n "$IMAGE_MARKUP" ]; then
          # Append images to the README file
          echo -e "$IMAGE_MARKUP" >> "$README_FILE"
        else
          echo "No images found in $IMAGES_DIR"
        fi

    - name: Commit changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token for authentication
      run: |
        git config --local user.name "GitHub Action"
        git config --local user.email "action@github.com"
        if [ -f "$README_FILE" ]; then
          git add "$README_FILE"
          git commit -m "Update README with images from the images directory" || echo "No changes to commit"
          git push
        else
          echo "$README_FILE does not exist in the repository's root directory."
        fi
